### ISSUE TITLE
Javascript <script> balise no longer formatted

### ISSUE THREAD

**Issue by kodewu** [calumk/editorjs-codeflask#14]
Hello, 

when I use this code, the javascript <script> saved in JSON format is no longer formatted.
I give you an example:

Before save, my course (not working):
![image](https://github.com/calumk/editorjs-codeflask/assets/65669857/66a1c43a-df26-470f-844f-21a6374283e2)

After save my course: 
![image](https://github.com/calumk/editorjs-codeflask/assets/65669857/fb125b1d-68eb-4a1e-8ded-9af3447f5384)

The value of fd : 
`const fd = {"time":1703516558675,"blocks":[{"id":"IQzcrAghZ1","type":"paragraph","data":{"text":"This this a p text.","alignment":"left"}},{"id":"tIkUdrt3Lk","type":"code","data":{"code":"<script>alert(\"Hello World\");</script>","language":"js","showlinenumbers":true}}],"version":"2.26.5"};`

Without script balise (working):
![image](https://github.com/calumk/editorjs-codeflask/assets/65669857/5636781c-ce6c-4d50-9c19-10fae082f51c)

Thanks for your help,
Florent.

**Comment by calumk** [comment]
Huh, this is interesting

**Comment by kodewu** [comment]
Yeah, it's true, I haven't found a solution yet. It's almost driven me crazy not finding it. 

I don't know if anyone has been able to discover my problem and/or solve it?

**Comment by kodewu** [comment]
Hello @calumk :)
Do you think a solution is possible to solve my problematic ?
Thanks in advance.

**Comment by calumk** [comment]
@flomirtech yes 

I actually worked on this yesterday, but not yet updated 

Hopefully I will finish tonight

**Comment by kodewu** [comment]
Great, if it works, I'll be delighted!

**Comment by calumk** [comment]
> [!IMPORTANT]
> This repo will be archived soon. Please upgrade to [@calumk/editorjs-codecup](http://github.com/calumk/editorjs-codecup)

This should solve your issue - please test for me

**Comment by kodewu** [comment]
Thanks for your job @calumk. I can't wait to try this out!

Just, is your CDN link dead?
Couldn't find the requested file /dist/editorjs-codecup.bundle.min.js in @calumk/editorjs-codecup.
=> https://cdn.jsdelivr.net/npm/@calumk/editorjs-codecup
